version: "3"
services:
  postgres:
    image: postgres
    container_name: planning-poker-dev-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      TZ: 'Asia/Saigon'
      PGTZ: 'Asia/Saigon'
    ports:
      - 5434:5432
  postgres-test:
    image: postgres
    container_name: planning-poker-test-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      TZ: 'Asia/Saigon'
      PGTZ: 'Asia/Saigon'
    ports:
      - 5435:5432