name: Deploy on server production (Planning Pocker Backend)

env:
  APP_ENV: ${{ secrets.APP_ENV }}

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Extract env file multi line.
        run: |
          rm -r -f .env
          touch .env_temp
          echo $APP_ENV | tee .env_temp
          sed 's/ /\n/g' .env_temp >> .env
          rm -r -f .env_temp

      - name: Docker
        run: |
          docker build -t planning-pocker-backend .
          docker save -o planning-pocker-backend.tar planning-pocker-backend

      - name: Copy Docker image to ec2 use SSH Key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.PROD_SERVER_KEY_SSH }}
          source: "planning-pocker-backend.tar,docker-compose-ssh.yml"
          target: "~/planning-pocker-backend"

      - name: Executing remote ssh commands using SSH Key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.PROD_SERVER_KEY_SSH }}
          script_stop: true
          script: |
            cd ~/planning-pocker-backend
            sudo snap install docker
            sudo docker load --input planning-pocker-backend.tar
            sudo docker-compose -f docker-compose-ssh.yml  up -d --force-recreate
            rm -rf planning-pocker-backend.tar
            sudo docker image prune -a -f
